version: '3.4'

services:
  tmnfdocker:
    image: ksmarty/tmnf-docker
    container_name: tmnf_server
    volumes:
      - socket:/run/mysqld/
    ports:
      - 2350:2350/tcp # Server
      - 2350:2350/udp # Server
      - 3450:3450/tcp # P2P
      - 3450:3450/udp # P2P
      # - 5000:5000     # RPC
    env_file: ./secrets.example
    restart: unless-stopped
  db:
    image: mariadb
    container_name: tmnf_db
    volumes:
      - socket:/run/mysqld/
    env_file: ./secrets.example
    restart: unless-stopped

networks:
  default:


volumes:
  socket:
